### ISSUE TITLE
Statistics updating genomes blocks db

### ISSUE THREAD

**Issue by shanewilson** [capsid/capsid#36]
When running 'capsid statistics' the final step that calculates the number of samples with reads that hit each genome seems to freeze the db - nothing else can be done while this is running. Also is seem to take a really long time.

**Comment by iborozan** [comment]
could be due to the multiprocessing implementation

**Comment by shanewilson** [comment]
moves gen/sample update to python so it doesnt kill the db

https://github.com/capsid/capsid-pipeline/commit/f36a8cb8be50cd10ff0ed9330a64728cd501f57a
